skips:
- B101
- B311
- B113  # `Requests call without timeout` these requests are done in the benchmark and examples scripts only
- B403  # We are using pickle for tests only
- B404  # Using subprocess library
- B602  # subprocess call with shell=True identified
- B110  # Try, Except, Pass detected.
- B104  # Possible binding to all interfaces.
- B301  # Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue.